[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools >= 75.8, < 75.9",
]

[project]
name = "mlrl-common"
description = "Provides common modules to be used by different types of multi-label rule learning algorithms"
readme = "README.md"
authors = [
    { name = "Michael Rapp", email = "michael.rapp.ml@gmail.com" },
]
keywords = [
    "machine learning",
    "multi-label classification",
    "multi-output regression",
    "multi-target regression",
    "rule learning",
    "scikit-learn",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: C++",
    "Programming Language :: Cython",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "numpy",
    "scikit-learn",
    "scipy",
]
dynamic = [
    "optional-dependencies",
]

[project.urls]
homepage = "https://github.com/mrapp-ke/MLRL-Boomer"
source = "https://github.com/mrapp-ke/MLRL-Boomer.git"
download = "https://github.com/mrapp-ke/MLRL-Boomer/releases"
changelog = "https://raw.githubusercontent.com/mrapp-ke/MLRL-Boomer/refs/heads/main/CHANGELOG.md"
documentation = "https://mlrl-boomer.readthedocs.io/en/latest"
issues = "https://github.com/mrapp-ke/MLRL-Boomer/issues"
