[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools >= 76.0, < 76.1",
]

[project]
name = "mlrl-seco"
description = "A scikit-learn implementation of a Separate-and-Conquer (SeCo) multi-label rule learning algorithm"
readme = "README.md"
authors = [
    { name = "Michael Rapp", email = "michael.rapp.ml@gmail.com" },
]
keywords = [
    "machine learning",
    "multi-label classification",
    "rule learning",
    "scikit-learn",
    "separate-and-conquer",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: C++",
    "Programming Language :: Cython",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "mlrl-common",
]

[project.optional-dependencies]
testbed = ["mlrl-testbed"]

[project.urls]
homepage = "https://github.com/mrapp-ke/MLRL-Boomer"
source = "https://github.com/mrapp-ke/MLRL-Boomer.git"
download = "https://github.com/mrapp-ke/MLRL-Boomer/releases"
changelog = "https://raw.githubusercontent.com/mrapp-ke/MLRL-Boomer/refs/heads/main/CHANGELOG.md"
documentation = "https://mlrl-boomer.readthedocs.io/en/latest"
issues = "https://github.com/mrapp-ke/MLRL-Boomer/issues"
