---
ci:
  - all:
      - changed-files:
          - any-glob-to-any-file: .github/**
build-system:
  - all:
      - changed-files:
          - any-glob-to-any-file: build_system/**
          - all-globs-to-all-files: '!build_system/res/**'
documentation:
  - all:
      - changed-files:
          - any-glob-to-any-file: doc/**
common:
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - python/subprojects/common/**
              - cpp/subprojects/common/**
boosting:
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - python/subprojects/boosting/**
              - cpp/subprojects/boosting/**
seco:
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - python/subprojects/seco/**
              - cpp/subprojects/seco/**
testbed:
  - all:
      - changed-files:
          - any-glob-to-any-file: python/subprojects/testbed/**
testbed-arff:
  - all:
      - changed-files:
          - any-glob-to-any-file: python/subprojects/testbed-arff/**
testbed-sklearn:
  - all:
      - changed-files:
          - any-glob-to-any-file: python/subprojects/testbed-sklearn/**
util:
  - all:
      - changed-files:
          - any-glob-to-any-file: python/subprojects/util/**
tests:
  - all:
      - changed-files:
          - any-glob-to-any-file: python/tests/**
