version: 2
build:
  os: "ubuntu-lts-latest"
  tools:
    python: "latest"
  apt_packages:
    - doxygen
  commands:
    - GPU_SUPPORT=disabled ./build doc
    - mkdir $READTHEDOCS_OUTPUT
    - ln -s doc/_build/html $READTHEDOCS_OUTPUT
