version: 2
build:
  os: "ubuntu-lts-latest"
  tools:
    python: "latest"
  apt_packages:
    - doxygen
    - opencl-headers
    - ocl-icd-opencl-dev
  commands:
    - export READTHEDOCS_OUTPUT="doc/_build"
    - ./build doc
