version: 2
build:
  os: "ubuntu-lts-latest"
  tools:
    python: "latest"
  apt_packages:
    - doxygen
  commands:
    - export READTHEDOCS_OUTPUT="doc/_build"
    - GPU_SUPPORT=disabled ./build doc
