#!/bin/sh

VENV_DIR="venv"
BUILD_SYSTEM_DIR="build_system"
CLEAN=false

set -e

if [ $# -eq 1 ]; then
    if [ $1 = "--clean" ]; then
        CLEAN=true
    fi
    if [ $1 = "-c" ]; then
        CLEAN=true
    fi
fi

if [ ! -d $VENV_DIR ]; then
    echo "Creating virtual Python environment..."
    python3 -m venv ${VENV_DIR}
fi

if [ -d "$VENV_DIR" ]; then
    . $VENV_DIR/bin/activate
    python3 $BUILD_SYSTEM_DIR/main.py $@
    deactivate
fi

if [ $CLEAN = true ] && [ -d $VENV_DIR ]; then
    echo "Removing virtual Python environment..."
    rm -rf $VENV_DIR
    rm -rf $BUILD_SYSTEM_DIR/build
fi
