[tool.pylint.basic]

# Good variable names which should always be accepted, separated by a comma.
good-names = [
    "_",
    "i",
    "j",
    "k",
    "x",
    "y",
]

[tool.pylint.design]

# Minimum number of public methods for a class (see R0903).
min-public-methods = 0

[tool.pylint.format]

# Maximum number of characters on a single line.
max-line-length = 120

[tool.pylint."messages control"]

# Disable the message, report, category or checker with the given id(s). You
# can either give multiple identifiers separated by comma (,) or put this
# option multiple times (only on the command line, not in the configuration
# file where it should appear only once). You can also use "--disable=all" to
# disable everything first and then re-enable specific checks. For example, if
# you want to run only the similarities checker, you can use "--disable=all
# --enable=similarities". If you want to run only the classes checker, but have
# no Warning level messages displayed, use "--disable=all --enable=classes
# --disable=W".
disable = [
    "duplicate-code",
    "import-error",
    "no-name-in-module",
    "too-many-ancestors",
    "too-many-arguments",
    "too-many-instance-attributes",
    "too-many-lines",
    "too-many-locals",
    "too-many-positional-arguments",
    "too-many-public-methods",
    "too-many-statements",
    "wrong-import-order",
]

[string]

# This flag controls whether inconsistent-quotes generates a warning when the
# character used as a quote delimiter is used inconsistently within a module.
check-quote-consistency = "yes"
