name: 'cbuildwheel'
on:
  push:
    branches: [ development ]
jobs:
  cbuildwheel:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.0
        env:
          CIBW_BEFORE_BUILD: make wheel
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: './wheelhouse/*whl'
          if-no-files-found: error
