name: 'Manylinux'
on:
  push:
    branches: [ development ]
  release:
    types: [ published ]
    branches: [ master ]
jobs:
  manylinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Build
        uses: ./.github/workflows/manylinux/
