name: 'Manylinux'
on:
  push:
    branches: [ development ]
  release:
    types: [ published ]
    branches: [ master ]
runs:
  using: 'docker'
  image: 'Dockerfile'
jobs:
  manylinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
