name: 'Manylinux'
on:
  push:
    branches: [ development ]
  release:
    types: [ published ]
    branches: [ master ]
jobs:
  manylinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./.github/workflows/manylinux/
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: './wheelhouse'
          if-no-files-found: error
