name: 'Publish Linux Packages'
on:
  release:
    types: [ published ]
    branches: [ master ]
jobs:
  manylinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Manylinux x86_64
        uses: ./.github/actions/manylinux_x86_64/
        with:
          python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: './wheelhouse/out/'
          if-no-files-found: error
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          TWINE_REPOSITORY: ${{ secrets.PYPI_REPOSITORY }}
        run: |
          pip install --upgrade pip
          pip install twine
          twine upload --non-interactive wheelhouse/out/*
        continue-on-error: true
