---
name: Publish release packages
on:
  release:
    types:
      - published
jobs:
  workflow_python_version:
    name: Determine Python version for workflow
    runs-on: ubuntu-slim
    outputs:
      workflow_python_version: ${{ steps.workflow_python_version.outputs.workflow_python_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: build_system/res/versioning/version-python
          sparse-checkout-cone-mode: false
      - name: Determine Python version for workflow
        id: workflow_python_version
        run: echo "workflow_python_version=$(sed s/,//g build_system/res/versioning/version-python)" >> $GITHUB_OUTPUT
  publish_packages:
    needs: workflow_python_version
    name: Publish wheel packages
    uses: ./.github/workflows/template_publish.yml
    with:
      workflow_python_version: ${{ needs.workflow_python_version.outputs.workflow_python_version }}
      release: true
      linux: true
      macos: true
      windows: true
    secrets: inherit
  upload_to_pypi:
    needs: publish_packages
    name: Upload wheels to PyPI
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v8
        with:
          pattern: wheels-*
          path: wheelhouse
          merge-multiple: true
      - name: Upload wheels to PyPI
        uses: pypa/gh-action-pypi-publish@v1.14.0
        with:
          packages-dir: wheelhouse
          skip-existing: true
