name: Publish development packages
on:
  push:
    branches:
      - 'main'
    paths:
      - 'cpp/**/include/**'
      - 'cpp/**/src/**'
      - '**/*.pxd'
      - '**/*.pyx'
      - 'python/**/mlrl/**'
jobs:
  update_development_version:
    name: Update development version
    if: "!contains(github.event.head_commit.message, '[Bot]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup git
        uses: fregante/setup-git-user@v2
      - name: Update development version
        run: |
          ./build increment_development_version
          git add VERSION.dev
          git commit -m "[Bot] Update development version to $(cat VERSION.dev)."
          git push
  publish_packages:
    name: Publish wheel packages
    needs: update_development_version
    uses: ./.github/workflows/template_publish.yml
    with:
      pypi_repository: testpypi
      dev_release: true
    secrets:
      pypi_username: ${{ secrets.TEST_PYPI_USERNAME }}
      pypi_password: ${{ secrets.TEST_PYPI_PASSWORD }}
