---
name: Trigger release
on: workflow_dispatch
jobs:
  update_changelog:
    name: Update changelog
    uses: ./.github/workflows/template_update_changelog.yml
    with:
      release_branch: ${{ github.ref_name }}
    secrets:
      token_app_id: ${{ secrets.TOKEN_APP_ID }}
      token_app_secret: ${{ secrets.TOKEN_APP_SECRET }}
  release:
    needs: update_changelog
    name: Publish release on GitHub
    uses: ./.github/workflows/template_release.yml
    with:
      release_branch: ${{ github.ref_name }}
      release_version: ${{ needs.update_changelog.outputs.release_version }}
      changelog: ${{ needs.update_changelog.outputs.latest_changelog }}
    secrets:
      token_app_id: ${{ secrets.TOKEN_APP_ID }}
      token_app_secret: ${{ secrets.TOKEN_APP_SECRET }}
