---
name: Trigger release
on: workflow_dispatch
jobs:
  update_changelog:
    name: Update changelog
    uses: ./.github/workflows/template_update_changelog.yml
    with:
      release_branch: ${{ github.ref_name }}
    secrets: inherit
  build_doc:
    needs: update_changelog
    name: Build documentation
    uses: ./.github/workflows/template_publish_doc.yml
    with:
      release: true
    secrets: inherit
  release:
    needs: build_doc
    name: Publish release on GitHub
    uses: ./.github/workflows/template_release.yml
    with:
      release_branch: ${{ github.ref_name }}
    secrets: inherit
