---
name: Trigger release
on: workflow_dispatch
jobs:
  update_changelog:
    name: Update changelog
    uses: ./.github/workflows/template_update_changelog.yml
    with:
      release_branch: ${{ github.ref_name }}
    secrets: inherit
  build_doc:
    needs: update_changelog
    name: Build documentation
    uses: ./.github/workflows/template_publish_doc.yml
    with:
      release: true
    secrets: inherit
  release:
    needs: build_doc
    name: Publish release on GitHub
    uses: ./.github/workflows/template_release.yml
    with:
      release_branch: ${{ github.ref_name }}
      release_version: ${{ needs.update_changelog.outputs.release_version }}
      changelog: ${{ needs.update_changelog.outputs.latest_changelog }}
    secrets: inherit
  close_milestone:
    needs: update_changelog
    name: Close milestone
    runs-on: ubuntu-24.04
    steps:
      - name: Close milestone
        uses: Beakyn/gha-close-milestone@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: ${{ github.repository }}
          milestone-title: ${{ needs.update_changelog.outputs.release_version }}
