---
name: Close milestone
on:
  workflow_call:
    inputs:
      release_branch:
        required: true
        type: string
jobs:
  release:
    name: Close milestone
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_branch }}
      - name: Determine release version
        uses: juliangruber/read-file-action@v1
        id: release_version
        with:
          path: build_system/res/versioning/version
      - name: Close milestone
        uses: Beakyn/gha-close-milestone@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: ${{ github.repository }}
          milestone-title: ${{ steps.release_version.outputs.content }}
