---
name: Publish Linux wheels
on:
  workflow_call:
    inputs:
      subproject:
        required: true
        type: string
      release:
        required: false
        type: boolean
env:
  SUBPROJECTS: ${{ inputs.subproject }}
  RELEASE: ${{ inputs.release == true }}
  TEST_SUPPORT: disabled
  GPU_SUPPORT: disabled
jobs:
  publish_linux_wheels:
    name: Publish ${{ inputs.subproject }} (Linux)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Determine minimum Python version
        uses: juliangruber/read-file-action@v1
        id: python_version
        with:
          path: .version-python
      - name: Build package
        uses: pypa/cibuildwheel@v2.22
        env:
          CIBW_ENVIRONMENT_PASS_LINUX: SUBPROJECTS RELEASE TEST_SUPPORT GPU_SUPPORT
          CIBW_BEFORE_BUILD: ./build --clean && ./build pyproject_toml
          CIBW_BUILD_FRONTEND: build
          CIBW_ARCHS: auto64
          CIBW_SKIP: pp* *musllinux*
          CIBW_PROJECT_REQUIRES_PYTHON: ${{ steps.python_version.outputs.content }}
        with:
          package-dir: python/subprojects/${{ inputs.subproject }}/
      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ inputs.subproject }}-${{ runner.os }}-${{ runner.arch }}
          path: wheelhouse/*.whl
          if-no-files-found: error
