---
name: Publish pure wheels
on:
  workflow_call:
    inputs:
      subproject:
        required: true
        type: string
      release:
        required: false
        type: boolean
      pypi_repository:
        required: false
        type: string
jobs:
  publish_pure_wheels:
    name: Publish ${{ inputs.subproject }} (pure)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build package
        run: |
          RELEASE=${{ inputs.release == true }} SUBPROJECTS=${{ inputs.subproject }} ./build build_wheels
          mkdir wheelhouse
          cp python/subprojects/**/dist/*.whl wheelhouse/
      - name: Setup Python
        if: ${{ inputs.pypi_repository }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Upload wheels to PyPI
        if: ${{ inputs.pypi_repository }}
        env:
          TWINE_USERNAME: ${{ secrets.pypi_username }}
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
          TWINE_REPOSITORY: ${{ inputs.pypi_repository }}
        run: |
          python -m pip install twine
          python -m twine upload --non-interactive --skip-existing wheelhouse/*
      - name: Upload wheels as artifacts
        if: ${{ inputs.pypi_repository }}
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ inputs.subproject }}-any
          path: wheelhouse/*.whl
          if-no-files-found: error
