---
name: Run wheel
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      subproject:
        required: true
        type: string
      workflow_python_version:
        required: true
        type: string
jobs:
  python_versions:
    name: Determine Python versions supported by ${{ inputs.subproject }} (${{ inputs.os }})
    runs-on: ${{ inputs.os }}
    outputs:
      python_versions: ${{ steps.python_versions.outputs.python_versions || steps.python_versions_windows.outputs.python_versions }}
    steps:
      - name: Enable support for long paths
        if: ${{ startsWith(inputs.os, 'windows-') }}
        run: git config --system core.longpaths true
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            build_system
            python
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.workflow_python_version }}
          check-latest: true
          cache: pip
          cache-dependency-path: '**/requirements.txt'
      - name: Determine supported Python versions
        uses: juliangruber/read-file-action@v1
        id: python_version
        with:
          path: build_system/res/versioning/version-python
      - name: Create virtual environment
        if: ${{ !startsWith(inputs.os, 'windows-') }}
        run: ./build venv
      - name: Create virtual environment
        if: ${{ startsWith(inputs.os, 'windows-') }}
        run: .\build.bat venv
      - name: Determine built Python versions
        id: python_versions
        if: ${{ !startsWith(inputs.os, 'windows-') }}
        env:
          CIBW_PACKAGE_DIR: python/subprojects/${{ inputs.subproject }}
          CIBW_ARCHS: auto64
          CIBW_PROJECT_REQUIRES_PYTHON: ${{ steps.python_version.outputs.content }}
        run: echo "python_versions=$(./build print_cibuildwheel_python_versions)" >> $GITHUB_OUTPUT
      - name: Determine built Python versions
        id: python_versions_windows
        if: ${{ startsWith(inputs.os, 'windows-') }}
        env:
          CIBW_PACKAGE_DIR: python/subprojects/${{ inputs.subproject }}
          CIBW_ARCHS: auto64
          CIBW_PROJECT_REQUIRES_PYTHON: ${{ steps.python_version.outputs.content }}
          CIBW_SKIP: cp???t-win*
        run: echo "python_versions=$(.\build.bat print_cibuildwheel_python_versions)" >> $env:GITHUB_OUTPUT
  run_wheel:
    needs: python_versions
    name: Run wheel ${{ inputs.subproject }} (${{ inputs.os }})
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
      matrix:
        python_version: ${{ fromJson(needs.python_versions.outputs.python_versions) }}
    steps:
      - name: Enable support for long paths
        if: ${{ startsWith(inputs.os, 'windows-') }}
        run: git config --system core.longpaths true
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            build_system
            python
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}
          check-latest: true
          cache: pip
          cache-dependency-path: '**/requirements.txt'
      - name: Create virtual environment
        if: ${{ !startsWith(inputs.os, 'windows-') }}
        run: ./build install_runtime_dependencies
      - name: Create virtual environment
        if: ${{ startsWith(inputs.os, 'windows-') }}
        run: .\build.bat install_runtime_dependencies
      - name: Download wheels
        uses: actions/download-artifact@v8
        with:
          pattern: wheels-*
          path: wheelhouse
          merge-multiple: true
      - name: Install wheels
        if: ${{ !startsWith(inputs.os, 'windows-') }}
        env:
          PACKAGE_NAME: mlrl-${{ inputs.subproject == 'boosting' && 'boomer' || inputs.subproject }}
        run: |
          .venv/bin/uv pip install --find-links wheelhouse --no-index --no-deps mlrl-util
          .venv/bin/uv pip install --find-links wheelhouse --no-index --no-deps mlrl-testbed
          .venv/bin/uv pip install --find-links wheelhouse --no-index --no-deps mlrl-testbed-arff
          .venv/bin/uv pip install --find-links wheelhouse --no-index --no-deps mlrl-testbed-sklearn
          .venv/bin/uv pip install --find-links wheelhouse --no-index --no-deps mlrl-common
          .venv/bin/uv pip install --find-links wheelhouse --no-index --no-deps $PACKAGE_NAME
      - name: Install wheels
        if: ${{ startsWith(inputs.os, 'windows-') }}
        env:
          PACKAGE_NAME: mlrl-${{ inputs.subproject == 'boosting' && 'boomer' || inputs.subproject }}
        run: |
          .\.venv\Scripts\uv pip install --find-links wheelhouse --no-index --no-deps mlrl-util
          .\.venv\Scripts\uv pip install --find-links wheelhouse --no-index --no-deps mlrl-testbed
          .\.venv\Scripts\uv pip install --find-links wheelhouse --no-index --no-deps mlrl-testbed-arff
          .\.venv\Scripts\uv pip install --find-links wheelhouse --no-index --no-deps mlrl-testbed-sklearn
          .\.venv\Scripts\uv pip install --find-links wheelhouse --no-index --no-deps mlrl-common
          .\.venv\Scripts\uv pip install --find-links wheelhouse --no-index --no-deps $env:PACKAGE_NAME
      - name: Run wheel
        if: ${{ !startsWith(inputs.os, 'windows-') }}
        run: .venv/bin/mlrl-testbed mlrl.${{ inputs.subproject }} --version
      - name: Run wheel
        if: ${{ startsWith(inputs.os, 'windows-') }}
        run: .\.venv\Scripts\mlrl-testbed mlrl.${{ inputs.subproject }} --version
