name: 'Test build'
on:
  push:
    paths:
      - '**/*.hpp'
      - '**/*.cpp'
      - '**/*.pxd'
      - '**/*.pyx'
      - '**/*.py'
      - '**/*.build'
      - 'scons/**'
      - '**/requirements.txt'
      - 'doc/**'
      - 'python/subprojects/testbed/tests/**'
      - '.github/workflows/test_build.yml'
jobs:
  linux_build:
    name: Test Linux build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install OpenCL
        run: |
          sudo apt update
          sudo apt install -y opencl-headers ocl-icd-opencl-dev
      - name: Install GoogleTest
        run: sudo apt install -y googletest
      - name: Compile via GCC
        run: ./build compile
      - name: Test C++ code
        run: ./build tests_cpp
      - name: Test Python code
        run: ./build tests_python
      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1
      - name: Install Roboto font
        run: sudo apt install -y fonts-roboto
      - name: Generate Documentation
        run: ./build doc
  macos_build:
    name: Test MacOS build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install OpenMP
        run: |
          brew install libomp
          brew link libomp --force
      - name: Install OpenCL
        run: brew install opencl-clhpp-headers
      - name: Compile via Clang
        run: TEST_SUPPORT=disabled CPLUS_INCLUDE_PATH=/usr/local/opt/opencl-clhpp-headers/include ./build compile
  windows_build:
    name: Test Windows build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Remove conflicting link.exe
        uses: JesseTG/rm@v1.0.3
        with:
          path: C:\Program Files\Git\usr\bin\link.EXE
      - name: Install OpenCL
        uses: johnwason/vcpkg-action@v5
        with:
          pkgs: opencl
          triplet: x64-windows
          token: ${{ github.token }}
      - name: Compile via MSVC
        run: |
          $env:TEST_SUPPORT = "disabled"
          $env:INCLUDE += ";$($pwd.Path)\vcpkg\packages\opencl_x64-windows\include"
          $env:LIB += ";$($pwd.Path)\vcpkg\packages\opencl_x64-windows\lib"
          ./build.bat compile
