name: 'Integration Tests'
on:
  push:
    paths:
      - '**/*.hpp'
      - '**/*.cpp'
      - '**/*.pxd'
      - '**/*.pyx'
      - '**/*.py'
      - '.github/workflows/test_integration.yml'
jobs:
  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: |
          make tests
