name: Check for disallowed file changes
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      any: ${{ steps.filter.outputs.any }}
    steps:
      - name: Look up Git repository in cache
        uses: actions/cache/restore@v4
        with:
          path: .git/
          key: test-file-changes-cache-git-${{ github.run_id }}
          restore-keys: |
            test-file-changes-cache-git
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            any:
              - 'VERSION'
              - 'VERSION.dev'
      - name: Save Git repository to cache
        uses: actions/cache/save@v4
        if: success() || failure()
        with:
          path: .git/
          key: test-file-changes-cache-git-${{ github.run_id }}
  fail_on_file_changes:
    name: Fail on disallowed file changes
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - name: Fail on disallowed file changes
        if: ${{ !contains(github.event.head_commit.message, '[Bot]') && needs.changes.outputs.any == 'true' }}
        run: exit 1
