name: 'Integration Tests'
on:
  push:
    paths:
      - '**/*.hpp'
      - '**/*.cpp'
      - '**/*.pxd'
      - '**/*.pyx'
      - '**/*.py'
      - '.github/workflows/test_integration.yml'
jobs:
  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile
        run: |
          make compile
      - name: Install
        run: |
          make install
      - name: Run Tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s python/subprojects/testbed/tests -v
          deactivate
